# ── MLflow tracking (excluded from cfg_hash) ──

# Note: we use ${hydra:runtime.cwd} to ensure paths are always absolute from the root
# regardless of whether the script is run from root or a subfolder like notebooks/
# tracking_uri: sqlite:///${hydra:runtime.cwd}/outputs/mlflow.db
# artifact_location: ${hydra:runtime.cwd}/outputs/mlruns

tracking_uri: https://dagshub.com/valesin/ConTopo.mlflow
artifact_location: s3://contopotest/mlruns
artifact_cache_dir: ${hydra:runtime.cwd}/outputs/mlflow_artifact_cache
experiment_name: contopo2
enable_system_metrics: false
