ensembles:
  - ensemble_name: CE_rho5
    models:
      - name: CE_rho5
    metadata:
      rho: 5
      state: full
  - ensemble_name: CE_rho1
    models:
      - name: CE_rho1
    metadata:
      rho: 1
      state: full
  - ensemble_name: CE_rho0
    models:
      - name: CE_rho0
    metadata:
      rho: 0
      state: full
  - ensemble_name: CE_rho0.2
    models:
      - name: CE_rho0.2
    metadata:
      rho: 0.2
      state: full
  - ensemble_name: CE_rho0.04
    models:
      - name: CE_rho0.04
    metadata:
      rho: 0.04
      state: full
  - ensemble_name: CE_rho0.008
    models:
      - name: CE_rho0.008
    metadata:
      rho: 0.008
      state: full
